name: Build Flutter APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: |
          cd app/The_Silent_Voice
          flutter pub get

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses || true

      - name: Build APK
        run: |
          cd app/The_Silent_Voice
          flutter build apk --debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/The_Silent_Voice/build/app/outputs/flutter-apk/app-debug.apk
